USE sae51;
SET foreign_key_checks = 0;

LOAD DATA LOCAL INFILE '/etc/Ordinateur.csv' INTO TABLE Ordinateur FIELDS TERMINATED BY ',' IGNORE 1 ROWS ;

LOAD DATA LOCAL INFILE '/etc/Maintenance.csv' INTO TABLE  Maintenance FIELDS TERMINATED BY ',' IGNORE 1 ROWS ;

LOAD DATA LOCAL INFILE '/etc/Logiciel.csv' INTO TABLE Logiciel FIELDS TERMINATED BY ',' IGNORE 1 ROWS ;

LOAD DATA LOCAL INFILE '/etc/Utilisateur.csv' INTO TABLE Utilisateur FIELDS TERMINATED BY ',' IGNORE 1 ROWS ;

LOAD DATA LOCAL INFILE '/etc/Affectation.csv' INTO TABLE Affectation FIELDS TERMINATED BY ',' IGNORE 1 ROWS ;
